POST http://localhost:3333/login
Content-Type: application/json

{
    "name": "Kauezin",
    "key": "viniMeuAmore"
}

###
POST http://localhost:3333/registro
Content-Type: application/json

{
    "data": {    
        "nome": "admin",
        "tipoPonto": "admin",
        "horario": ""
        }
}